# -*- encoding: utf-8 -*-

# ---------------------------------------------------------------------------- #
# constants.py
#
# Various constants for the Hadron Assembler. This file is meant to be used
# by the tokenizer, parser and assembler.
# ---------------------------------------------------------------------------- #

# ------------------------------------ #
# Escape codes used in the tokenizer to correctly process strings and characters
ESCAPE_CODES = {
    r'\n': '\n',
    r'\a': '\a',
    r'\b': '\b',
    r'\v': '\v',
    r'\f': '\f',
    r'\0': '\0',
    r'\t': '\t',
    r'\r': '\r',
}

# ------------------------------------ #
# All warnings generated by the assembler during compilation
# By default and with no flags set, the assembler suppresses all warnings
# unless the verbosity is increased
WARNING_AS_ERRORS               = -1    # -Werror, treat warnings as errors
WARNING_BASE                    = 0     # Base warning
WARNING_ALL                     = 1     # -Wall

WARNING_LEVEL_PARSING           = 10    # All warnings related to parsing
WARNING_MULTILINE_STRING        = 11    # -Wmultiline-strings

# ------------------------------------ #
ERROR_BASE                      = 0
ERROR_FILE_NOT_FOUND            = 1
ERROR_OPENING_FILE              = 2
ERROR_INVALID_LITERAL           = 3

# ------------------------------------ #
# All assembly instructions
ALL_INSTRUCTIONS = [
    
]